### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by codenpixel** [yahia-raheem/tailwind-starter#1]
Great job! One small issue.
Good starter and I would like to stay on it but some things missing like here.Is it work on your side?
https://gist.github.com/kball/963b60881385458f425c866d10f13d74

**Comment by yahia-raheem** [comment]
well, actually the image optimization is almost complete ill push it later today probably .. as for panini i'll check it out.
also the live reload i'll probably add it later today or tomorrow, maybe the styleguide one too .. i mean, for all intents and purposes, if i just copy the function to my gulp file it should work too.
also if you want to use that gulp file instead of mine you can but you have to watch the directories structure (specially the html function) and be sure to copy the treeshaking function from mine it does wonders.

**Comment by codenpixel** [comment]
Thanks for the quick answer. I'm waiting for your update, I'll stick to this starter. It has potential.

**Comment by yahia-raheem** [comment]
thanks! .. hope you'll like it.
so i have updated the project with the three functions i told you about (images, server and auto reload, and styleguide generator) so let me know if you need any other functionality.
also take a look at my scss mixins and js helper functions you might like them too (scss mixins are already imported but the js ones you'll find there import commented in case you don't need them).
i probably need to update the documentation as soon as possible.

**Comment by codenpixel** [comment]
Great. I'll test and let you know if anything. Thanks

**Comment by yahia-raheem** [comment]
i'm closing this issue for now .. if you need anything else please let me know :)
